name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Test 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run containers
        run: docker-compose up -d

      - name: Start SSH tunnel
        run: |
          ssh -p 443 -R0:localhost:8000 -L4300:localhost:4300 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 4oDLH7Oqvhf@free.pinggy.io


      - name: Keep job alive for 15 minutes
        run: sleep 900
