name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  deploy:
    name: Docker container with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Run container
        run: docker-compose up -d 
      
      - name: Ngrok Tunnel
        uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          port: 8000
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          tunnel_type: http
          save_url_to_filename: tunnelURL.md
